name: CI
on:
  push:
    branches:
     - master
  workflow_dispatch:
env:
     PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
     HOST: ${{ secrets.HOST }}
     USER: ${{ secrets.USER }}  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v3
     - run: echo "${{ env.PRIVATE_KEY }}" > private_key
     - run: chmod 400 private_key
     - run: ls -rlt .
     - run: scp -o StrictHostKeyChecking=no -i private_key index.html ${{ env.USER }}@${{ env.HOST }}:/var/www/html/
     - run: ssh -o StrictHostKeyChecking=no -i private_key ${{ env.USER }}@${{ env.HOST }} '
            ls -rlt /var/www/html/ &&
            sudo systemctl restart httpd
            '
